pool:
  vmImage: 'Ubuntu 18.04'

variables:
  tagName: 'latest'
  imageName: '$(huiyuxu)/sit764-my-app:$(tagName)'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(huiyuxu) -p $(xhy.318524)
    docker push $(imageName)
  displayName: 'Push docker image'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'xuhuiyu123'
    runOptions: inline

    inline: |
     containers=$(docker ps -q --filter name=sit764-my-app)
     if test -n "$containers"; then
      docker stop $(docker ps -q --filter name=sit764-my-app) >> /dev/null 2>&1
      rc=$?
      if [[ $rc != 0 ]];
      then
       echo 'failed to stop container...'
       exit $rc;
      fi
     fi
     
     containers1=$(docker ps -q -a --filter name=sit764-my-app)
     if test -n "$containers1"; then
      docker rm $(docker ps -q -a --filter name=sit764-my-app) >> /dev/null 2>&1
      rc=$?
      if [[ $rc != 0 ]];
      then
       echo 'failed to remove container...'
       exit $rc;
      fi
     fi
     
     
     docker pull $(imageName) >> /dev/null 2>&1
     rc=$?
     if [[ $rc != 0 ]];
     then
      echo 'failed to pull container...'
      exit $rc;
     fi
     
     docker run -d -p 7010:80 --name sit764-my-app --link redis:redis-server $(imageName) >> /dev/null 2>&1
     rc=$?
     if [[ $rc != 0 ]];
     then
      echo 'failed to run container...'
      exit $rc;
     fi
     
     danglings=$(docker images -f "dangling=true" -q)
     if test -n "$danglings"; then
      docker rmi $(docker images -f "dangling=true" -q) >> /dev/null 2>&1
      rc=$?
      if [[ $rc != 0 ]];
      then
       echo 'failed to remove danglings container...'
       exit $rc;
      fi
     fi
