pool:
  vmImage: 'Ubuntu 18.04'

variables:
  tagName: 'latest'
  imageName: 'huiyuxu/sit764-my-app:$(tagName)'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u huiyuxu -p xhy.318524
    docker push $(imageName)
  displayName: 'Push docker image'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'xuhuiyu123'
    runOptions: inline

    inline: |
      kubectl set image huiyuxu/sit764-my-app sit764-my-app=$(imageName) --record=true