pool:
  vmImage: 'Ubuntu 18.04'

variables:
  tagName: 'latest'
  imageName: 'huiyuxu/sit764-my-app:$(tagName)'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u huiyuxu -p xhy.318524
    docker push $(imageName)
  displayName: 'Push docker image'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'xuhuiyu123'
    runOptions: inline

    inline: |
     containers=$(sudo docker ps -q --filter name=sit764-my-app)
     if test -n "$containers"; then
      sudo docker stop $(sudo docker ps -q --filter name=sit764-my-app) >> /dev/null 2>&1
      rc=$?
      if [[ $rc != 0 ]];
      then
       echo 'failed to stop container...'
       exit $rc;
      fi
     fi
     
     containers1=$(sudo docker ps -q -a --filter name=sit764-my-app)
     if test -n "$containers1"; then
      sudo docker rm $(sudo docker ps -q -a --filter name=sit764-my-app) >> /dev/null 2>&1
      rc=$?
      if [[ $rc != 0 ]];
      then
       echo 'failed to remove container...'
       exit $rc;
      fi
     fi
     
     
     sudo docker pull $(imageName) >> /dev/null 2>&1
     rc=$?
     if [[ $rc != 0 ]];
     then
      echo 'failed to pull container...'
      exit $rc;
     fi
     
     
     sudo docker run -i -t -d -p 80:80 $(tagName):nginx >> /dev/null 2>&1
     rc=$?
     if [[ $rc != 0 ]];
     then
      echo 'failed to run container...'
      exit $rc;
     fi  
     
   
